### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula por id
GET http://localhost:3000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar todas las peliculas por un genero
GET http://localhost:3000/movies?genre=action

### Crear una pelicula con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Shawshank Redemption",
    "year": 1994,
    "director": "Frank Darabont",
    "duration": 145,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
      "Drama",
      "Action"
    ],
    "rate": 10
}

### Borrar una pelicula
DELETE http://localhost:3000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Actualizar una pelicula
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "id": "dcdd0fad-a94c-4810-8acc-5f108d3b18c3",
  "year": 1990,
  "genre":[
    "Drama",
    "Action"
  ]
}

